from sqlalchemy.orm import Session
from . import models, schemas

def create_user(db: Session, user: schemas.UserCreate) -> models.User:
    """
    Creates a new user in the database.
    """
    # Create a new SQLAlchemy User model instance from the Pydantic schema data
    db_user = models.User(email=user.email, name=user.name)
    
    # Add the instance to the session
    db.add(db_user)
    
    # Commit the changes to the database
    db.commit()
    
    # Refresh the instance to get the data that was generated by the database (like the ID)
    db.refresh(db_user)
    
    return db_user